### ISSUE TITLE
No response to "Hello World" (console.log, either JavaScript or CoffeeScript)

### ISSUE THREAD

**Issue by ruipimentel** [lsegal/atom-runner#111]
I tried to run the following JavaScript code, properly saved to a "test.js" file in "/home/rui" (I'm running Atom 1.3.2 in Linux Mint 17.3 'Rosa' 64-bit; atom-runner version is 2.5.2).

`console.log("Hello world");`

Atom Runner displays:

    Atom Runner: test.js
    
    Exited with code=0 in 0.069 seconds

Note that the middle line (the one normally of darker color in the editor), where the resulting "Hello world" was supposed to be visible, is actually blank.

Just for testing sake, I tried the same code, but this time in CoffeeScript:

`console.log "Hello world"`

Which results in:

    Atom Runner: test.js
    coffee> 
    Exited with code=0 in 0.117 seconds

Final note: both versions ran successfully in a terminal window, in a direct call for "nodejs" and "coffee" respectively.

Does anyone know what might be happening?

**Comment by lsegal** [comment]
I'm curious if the background and foreground colors might be the same-- did you try highlighting the line to see if that was the case?

**Comment by ruipimentel** [comment]
Mmmm good guess, I haven't thought of that, but unfortunately this wasn't the case; I tried to highlight, and even copy/paste the lines again, but most definitely there is no text there :/

**Comment by ruipimentel** [comment]
Just out of fun, I modified the 'defaultScopeMap' setting for 'js' (in "atom-runner.coffee") as following:

```coffeescript
    // ...
    defaultScopeMap:
        // ...
        js: 'ls'
        // ...
```

Note: I modified "atom-runner.coffee" itself because "~/.atom/config.cson" didn't seem to cause any change to atom-runner's behavior.

But the interesting part is that, despite the fact that the normal behavior of a "`ls /home/rui/test.js`" command would be outputting "`/home/rui/test.js`", what I actually got in my "Atom Runner: test.js" tab was:

    Atom Runner: test.js
    Desktop
    Documents
    Downloads
    Music
    Pictures
    Public
    Templates
    test.js
    Videos
    Exited with code=0 in 0.026 seconds

Any ideas? :)

**Comment by lsegal** [comment]
Well my guess would be that whatever executable you're using for JavaScript files is not correctly providing output. The `coffee` portion of your initial report is easily explained by the fact that coffee probably requires a special switch to run in non-interactive mode with data from stdin. By default, running `coffee` will load up interactive mode, which is why you see the `coffee>` REPL line. Check the coffee switches to see which one you can pass in to run without interactive mode on.

As for your regular JavaScript code, I assume you're using the default `node` setup? If not, can you provide more info on which executable you're using for JavaScript?

**Comment by ruipimentel** [comment]
Thanks for your response, @lsegal, but I double checked the output for both JavaScript and CoffeeScript executables (running `node /home/rui/test.js` and `coffee /home/rui/test.js`, respectively) in a Terminal window, and at least *there* the outputs were "Hello world" undoubtedly.

I don't know exactly ***how*** `atom-runner` passes parameters to the executables, but I tested all of the following on a Terminal window:

```shell
rui@ruispc ~ $ node /home/rui/test.js 
Hello world
rui@ruispc ~ $ node < /home/rui/test.js 
Hello world
rui@ruispc ~ $ cat /home/rui/test.js | node
Hello world
```

In Atom, though, I'm still getting the same responses as of my initial report. **Long note**: since then, I reinstalled NodeJS completely following the instructions from the official documentation [https://github.com/nodesource/distributions#deb], having the software version to be the last, v5.4.0. Both "node" and "nodejs" executables are available and seem to be the same.

Finally, and most importantly, with the test in my last report, I intended to show you that `ls` ran just as if it never received any parameters from `atom-runner`... Had it received a "`/home/rui/test.js`" parameter, it would have outputted only the specified file (like it did in Terminal), wouldn't it?

Thank you again, I really appreciate all your help... Atom Runner is the whole reason why I adapted so well to Atom, without this plug-in I don't think I would have left Notepad++.

**Comment by lsegal** [comment]
> I don't know exactly how atom-runner passes parameters to the executables, 

atom-runner runs in two different modes. If you are running a file that is saved on disk, atom-runner runs the executable as a command, appending the filename to the end of the arguments list in the command. If the command was `ls -l`, atom-runner would execute `ls -l /path/to/file`. If the file is not yet saved (an unnamed file / buffer), atom-runner will execute the command without any filename argument and pipe the contents of the file to the stdin pipe. This is also the case if you execute a selection instead of a whole saved file.

One thing you might try is running atom-runner on an unsaved buffer to see what it does in that case. Open a new file, write something inside it and execute (making sure either the language grammar is selected or you have a shebang line). If that works, maybe something is up with Atom on your specific Linux distro. I've honestly never heard of Linux Mint before-- I realize the chances of this being distro-specific are extremely low, but it seems to be the only thing that differs from my working environments, and this is the first time this issue has been raised.

I'm also curious if this happens with other languages, like Ruby, Python, or even Bash. Can you test a simple script in those languages?

**Comment by lsegal** [comment]
Also, if you load up `~/.atom/packages/atom-runner/lib/atom-runner.coffee`, you can add in a `console.log` statement around the line:

https://github.com/lsegal/atom-runner/blob/master/lib/atom-runner.coffee#L145

To `console.log(cmd, args)`

This should show you the full command of what atom-runner is actually executing.

**Comment by ruipimentel** [comment]
Hi @lsegal, first of all thanks for the clarifications and for your patience!

I did as you say and tested all of JS, Ruby, Python and Bash "hello world" programs in an unsaved buffer:

```javascript
#!/usr/bin/node
console.log("Hello world");
```
```ruby
#!/usr/bin/ruby
puts "Hello world"
```
```python
#!/usr/bin/env python
print "Hello world"
```
```shell
#!/bin/bash
echo "Hello world";
```

The results were all the same:

```
Atom Runner: untitled

Exited with code=0 in 0.004 seconds
```

Next, I inserted the following piece (right after 145, that you mentioned):

```coffeescript
view.append(
    "cmd: " + cmd + "\n" +
    "editor.getPath(): " + editor.getPath() + "\n" +
    "selection: " + selection + "\n" +
    "args: " + args + "\n" +
    "dir: " + dir + "\n"
)
```

Which results in:

```
Atom Runner: test.js
cmd: node
editor.getPath(): /home/rui/test.js
selection: true
args: /home/rui/test.js
dir: /home/rui
Exited with code=0 in 0.164 seconds
```

So, if I get this right, for some reason my environment detects a selection (`selection` evaluates to `true`), where most definitely there is **not** one?

Finally, commenting out `if !selection` in line 133 (`args.push(editor.getPath()) if !selection`) results in:

```
Atom Runner: test.js
Hello world
Exited with code=0 in 0.164 seconds
```

So... How to proceed about it?

**Comment by lsegal** [comment]
If `selection` is true, you are running the `run:selection` command instead of `run:file`. Ctrl+R on Linux is `run:file`, Ctrl+Shift+R is `run:selection`:

https://github.com/lsegal/atom-runner/blob/master/keymaps/atom-runner.cson#L10

Did you rebind the keys?

**Comment by ruipimentel** [comment]
Oh oh, my bad... :s
You're absolutely right, I misunderstood the instructions... I'

**Comment by ruipimentel** [comment]
Oh oh, my bad... :s
You're absolutely right, I misunderstood the instructions... I'm sorry for taking your time, but completely grateful for your help.
`atom-runner` is such an **excellent** extension, thank you for putting it together!!!
Congrats and sorry again!!! :)
