### ISSUE TITLE
how to run two different server

### ISSUE THREAD

**Issue by pitambar** [lsegal/atom-runner#122]
i am not able to run node server in two different ports. how to do that, currently only 1 server is active. for testing purpose i want to start 2 server. is there a way

**Comment by lsegal** [comment]
atom-runner is not designed to run multiple long-running processes at the same time. Specifically, it would not be possible to run the same script in parallel, since this breaks UX around restarting a script.

We *could* improve the runner support to run *multiple* files in parallel, but this doesn't sound like what you would want.

For long running processes, you're probably better off running a dedicated terminal window.
