### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jayparekhjp** [lsegal/atom-runner#129]
i have a 64 bit windows 8.1,i installed atom and then added atom-runner package for c/c++ purpose.
but whenever i hit alt+r, nothing happens.

**Comment by lsegal** [comment]
atom-runner is not configured to run C/C++ programs by default because they require non-trivial compilation steps. You can configure this if you want, but this would require running some script to compile-then-run your code. atom-runner will *not* do this for you. See the [README](https://github.com/lsegal/atom-runner/blob/master/README.md#configuring) for how to configure new  languages.
