### ISSUE TITLE
Can't run program under windows 10 and python 3.5

### ISSUE THREAD

**Issue by ClementAcher** [lsegal/atom-runner#150]
Hi, 

atom-runner seems to be a really nice tool, but I can't get it to work. When I try to run a script, it says : 

> Unable to find command: python3
Are you sure PATH is configured correctly?

ENV PATH: undefined

I have looked for a solution, and everything I have tried did not help. I have tried to reinstall Python, checking the "set environnement" option, then installing Atom again. I've got C:\Python35\Scripts\ and C:\Python35\, but it still doesn't work.

What could I do to make it works? 

Thanks

**Comment by lsegal** [comment]
Is python.exe in one of those directories? You must set your PATH to point to the directory the exe is in, not the root directory of python. You can test your install by running `python` from cmd.exe. If you can do this, Atom should work fine. If you cannot, you picked the wrong directory. There might be a `bin\` sub-directory depending on the install.

Closing since this is an environment issue.
