### ISSUE TITLE
Question: Does it run javascript ES6 code?

### ISSUE THREAD

**Issue by netsi1964** [lsegal/atom-runner#160]
Hi,

I have an example where I use ES6 spread features, which will not run in atom-runner.
## Code example

```
const a = {
  name: 'sten',
  age: 51,
};
console.log({
  ...a,
  age: 52,
});
```
## Result

```
dummy.js:6
  ...a,
  ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

It will not run. Can I somehow turn on ES6 features?

**Comment by nathamanath** [comment]
Hi,

Just saw this is sitting here,

ES6 seems to work fine out of the box with atom-runner because https://nodejs.org/en/docs/es6/
But your example needs 'babel-preset-stage-0' or higher to run.
You can try it on babeljs.io [with](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Cstage-0&code=const%20a%20%3D%20{%0A%20%20name%3A%20%27sten%27%2C%0A%20%20age%3A%2051%2C%0A}%3B%0Aconsole.log%28{%0A%20%20...a%2C%0A%20%20age%3A%2052%2C%0A}%29%3B), and [without](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&code=const%20a%20%3D%20{%0A%20%20name%3A%20%27sten%27%2C%0A%20%20age%3A%2051%2C%0A}%3B%0Aconsole.log%28{%0A%20%20...a%2C%0A%20%20age%3A%2052%2C%0A}%29%3B)

You could do the following to run this via atom-runner:

From project directory run

```bash
  npm install -g babel-cli
  npm install --save babel-preset-stage-0
```

then in your projects `.babelrc`

```json
  {
    "presets": ["stage-0"]
  }
```

next, in your atom `config.cson`

```json
  "*":
    ...
    "runner":
      ...
      "scopes":
        "js": "babel-node"
```

There is probably an easier way, but this will get your example running :)

**Comment by lsegal** [comment]
Closing since this is a question and not an issue. The answer above should get you going.

**Comment by marcellodesales** [comment]
@netsi1964 If you want to keep the CLI local to your project, install it as a dependency to your project... Change your `config.cson` to always execute the babel-node.js dependency. That simplifies even more.


```yml
$ cat ~/.atom/config.cson
"*":
  core:
    telemetryConsent: "no"
  "exception-reporting":
    userId: "f6be1b70-ae02-5868-9c8f-77c4394afabf"
  welcome:
    showOnStartup: false

  "runner":
      "scopes":
        "js": "./node_modules/babel-cli/bin/babel-node.js"
```

<img width="609" alt="screen shot 2017-05-02 at 10 10 18 am" src="https://cloud.githubusercontent.com/assets/131457/25629775/953f9db0-2f1f-11e7-8b2a-4493da74f72f.png">

**Comment by digita1-Anal0g** [comment]
@marcellodesales - I have babel-cli installed as a local dependency, but am not able to get it to work.  No other atom packages are installed other than atom-runner.  Below is what I'm getting:

<img width="667" alt="screen shot 2017-05-18 at 9 29 59 pm" src="https://cloud.githubusercontent.com/assets/6117939/26233304/463fb9d0-3c11-11e7-951c-391ee04c5b05.png">

Here's my config.cson

```
"*":
   "runner":
      "scopes":
        "js": "babel-node"
  "exception-reporting":
    userId: "38a1fc25-4ce2-4f9f-9037-0b95205a3125"
```

If I install globally, as @nathamanath mentioned, it works, but I'd like to leverage a local install instead.  Is there anything else I need to do?
