### ISSUE TITLE
wrong cirdir about python

### ISSUE THREAD

**Issue by dhqdqk** [lsegal/atom-runner#167]
# dir
~/git/python/python3/now.py
~/git/python/python3/test.py
# code in now.py
```
import os

with open(os.path.join(os.path.abspath('.'), 'test.py'), 'r') as f:
    for line in f.readlines():
        print(line.strip('\n'))
```
# atom-runner work wrong:
```
Traceback (most recent call last):
  File "~/git/python/python3/io-programme.py", line 12, in <module>
    with open(os.path.join(os.path.abspath('.'), 'test.py'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/git/test.py'
```
# error 
`os.path.abspath('.')` return wrong dir `~/git`, the correct dir is `~/git/python/python3`.
it works correctly in terminal.

i think that atom-runner taking  the project dir as the cirdir causes the problem. In this case, the project dir is `~/git`

**Comment by lsegal** [comment]
This is expected behavior. atom-runner uses the working directory that Atom provides it. If you want your working directory to be different, open the file through Atom's project directory behavior (open the directory instead of the file directly) or don't rely on paths relative to your working directory if you expect data in a specific location relative to your program. You should never assume that your program file is equal to your working directory.
