### ISSUE TITLE
Scala scripts are not executed correctly

### ISSUE THREAD

**Issue by hohonuuli** [lsegal/atom-runner#32]
I'm running atom-runer 2.2.0 in atom 0.169.0 and tried to add a new language, in this case Scala. However, atom-runner is not executing them as expected. I added the following to my _config.cson_ file:

```javascript
'runner':
  'scopes':
    'scala': 'scala'
```

Then, I created the following scala code:
```scala
#!/usr/bin/env scala
println("Hello")
```

When I use atom-runner to run it. ti dumps out the following:

```
Welcome to Scala version 2.11.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_71).
Type in expressions to have them evaluated.
Type :help for more information.

scala> #!/usr/bin/env scala
<console>:8: error: not found: value #!/
              #!/usr/bin/env scala
              ^
<console>:8: error: not found: value /
              #!/usr/bin/env scala
                    ^
<console>:8: error: not found: value /
              #!/usr/bin/env scala
                        ^
<console>:8: error: package scala is not a value
              #!/usr/bin/env scala
                             ^

scala> println("Hello")
Hello

scala> :quit

```

The problems are:

1. it's not actually running it as a script and capturing the output. 
2. It's passing the code directly to the scala interpreter including the shebang line, which is wrong. That line shouldn't be fed to scala.
3. If I remove the shebang line, then atom-runner won't run the code at all

Am I doing something wrong? I tried the same thing with Groovy and I run into the same kind of issues.

Thanks!

**Comment by lsegal** [comment]
I would recommend configuring the `-howtorun` option, since it doesn't seem like Scala would be making the right guess in your scenario. See http://www.scala-lang.org/old/sites/default/files/linuxsoft_archives/docu/files/tools/scala.html

As for the shebang, does Scala (or Groovy) support a shebang line? If not, adding that line won't work. Instead, you can detect Scala by using the `'extensions`' configuration setting in atom-runner to detect the file by file extension rather than grammar scope.
