### ISSUE TITLE
path point to atoms root directory instead of the program directory

### ISSUE THREAD

**Issue by picibucor** [lsegal/atom-runner#41]
Till now I could run my program within atom, with the help of atom-runner.
After upgrading from 0.177 to 0.182 I cannot.

As I tried to run my program, I got an error message:
FileNotFoundError: No such File or Directory: 'C:\Users\Username\AppData\Local\atom\app-0.182.0\...' 

It is no wonder, that my files are not found there. This path is where atom is installed, and not the path of my program. 

OS: Win7
language: Python 3.x

**Comment by picibucor** [comment]
It wasn't the runners issue, sorry

**Comment by picibucor** [comment]
I updated the atom-runner, and I got the same error-message...

**Comment by lsegal** [comment]
This plugin runs in the current working directory that atom provides. This is intentional behavior and would break others if this were to change. Incidentally this is how your program would behave from the shell, so if your program requires being run from a specific path, you should chdir to that path in your program.
