### ISSUE TITLE
c++

### ISSUE THREAD

**Issue by di48l069** [lsegal/atom-runner#68]
hey guys,

can this compile c++ and if it does how would i add c++ to it?

**Comment by lsegal** [comment]
See the "Configuring" section of the [README](https://github.com/lsegal/atom-runner) for info on adding extensions. Running a C++ source file depends heavily on your build process. Executing an individual cpp file would likely not work very well, but if you know which binary you want to run you could run `make && ./thebinary` as the command for the extension, or even just create a `make run` Makefile task, since there are no per-project settings

**Comment by di48l069** [comment]
hi i have tried pasting below in my config file

```
'runner':
  'scopes':
    'coffee': 'coffee'
    'js': 'node'
    'ruby': 'ruby'
    'python': 'python'
    'go': 'go run'
    'shell': 'bash'
    'powershell': 'c:\\windows\\sysnative\\windowspowershell\\v1.0\\powershell.exe -noninteractive -noprofile -c -'
  'extensions':
    'spec.coffee': 'mocha'
    'ps1': 'c:\\windows\\sysnative\\windowspowershell\\v1.0\\powershell.exe –file'
```

And i get a error am i doing something wrong can you show me example of your config file

**Comment by lsegal** [comment]
I don't see anything defining a cpp extension and command for that extension. A sample might be:

```
  'extensions':
    'cpp': 'make run'
```

Again, your mileage may vary based on how you run your C++ source files.

**Comment by di48l069** [comment]
thank you.
