### ISSUE TITLE
PATH and environment variable detection on Windows.

### ISSUE THREAD

**Issue by rduartes** [lsegal/atom-runner#71]
Extend the support for path and environment variables detection on Windows so that configurations for node and npm can be loaded. 

Currently trying to run a js script inside Atom fails because of failed dependencies as I have them installed globally and not locally and the since the env vars that configure the node package location is unavailable it fails to resolve it.

The same script executed on Windows command line works as expected.

**Comment by lsegal** [comment]
Patches accepted. I don't test this on Windows.

**Comment by unuunc** [comment]
Posted this on Closed issue -- Posting on open if helps 

I observed this occurs if path to executable contains spaces , I tested it by creating a soft link to my executable and it worked fine.
For example - FSharp
first I tried with "c:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsi.exe"
I got error which starts with "spawn c:\program ENOENT"
then I changed that to "%Programfiles(x86)%\Microsoft SDKs\F#\3.1\Framework\v4.0\fsi.exe"
I got error "spawn %Programfiles(x86)%\Microsoft ENOENT"

If you see error occurs at first space in path so I created a symlink to fsi say "D:\links\fsi\Fsi.exe"
And it started working.

**Comment by lsegal** [comment]
Unfortunately atom-runner does not currently support spaces in the command name portion because it also accepts arguments and cannot determine which portion is the executable and which are arguments (if any). The suggestion would be to use shorthand filenames or update your PATH to include these directories.

Patches accepted to fix this but there are no immediate plans to change behavior given the existence of reasonable workarounds.
